Revert "fix 'Uncaught TypeError: undefined is not a function', spacing in coffeescript Ember.ListView.extend functin"
This reverts commit 20daf3d7a91aa3e57617e3cea5338a9d64db5ae3.